# Generated by Django 5.0.6 on 2024-05-11 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pencatatanbarang', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pengembalian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_pengembalian', models.DateField(auto_now_add=True)),
                ('jumlah_dikembalikan', models.IntegerField()),
                ('barang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pengembalian', to='pencatatanbarang.barang')),
            ],
        ),
    ]
